server:
  port: 8070
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fkk?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: fkk
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.example.demo.mapper : debug
    #level的配置只能是key：value结构，如上，包名：级别